[package]
name = "commit-message"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.41", features = ["derive"] }
reqwest = { version = "0.12.22", features = ["blocking"] }
serde_json = "1.0.141"
tokio = { version = "1.46.1", features = ["full"] }
